favicon: /images/favicon.ico
banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: true
  thisSearch: https://www.baidu.com/s?wd=
  thisSearchIcon: url(/images/search/baidu.png)
  hotStatus: true
  data:
    - name: 百度
      img: url(/images/search/baidu.png)
      url: https://www.baidu.com/s?wd=
    - name: 谷歌
      img: url(/images/search/google.png)
      url: https://www.google.com/search?q=
    - name: 必应
      img: url(/images/search/bing.png)
      url: https://cn.bing.com/search?q=

githubCorner: '<a href="https://github.com/Vinx911" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

expandAll: false
menu:
  - name: 常用网址
    icon: far fa-star
    config: commonWebsite
    
  - name: 编程开发
    icon: fab fa-dev
    config: development
    
  - name: 技术论坛
    icon: far fa-comments
    config: forum
    
  - name: 帮助手册
    icon: fa fa-book
    config: manual   
    
  - name: 视频音乐
    icon: fas fa-bars
    config: videoMusic
    submenu:
      - name: 视频
        icon: fas fa-film
        config: video
      - name: 音乐
        icon: fas fa-music
        config: music
      - name: 直播
        icon: fas fa-video
        config: live
    
  - name: 在线教育
    icon: fas fa-university
    config: onlineEducation
        
  - name: 优秀博客
    icon: fas fa-globe
    submenu:
      - name: 开源期刊
        icon: fas fa-code
        config: journal
      - name: C/C++
        icon: fas fa-code
        config: excellent-C_CPP
      - name: Java
        icon: fas fa-code
        config: excellent-Java
    
  - name: 开源书籍
    icon: fas fa-book
    config: book   
        
  - name: 开发工具
    icon: fas fa-tools
    config: tools
    
  - name: UI资源
    icon: fas fa-icons
    config: uiResources

about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是Vinx的个人网址导航。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: Vinx
    url: https://blog.vinkvin.com/
    img: /images/logos/myblog.png
    description: 佛道两系少年(男人至死是少年)，自学成才的菜鸟

since: 2021

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
